linters-settings:
  gocognit:
    min-complexity: 10
  maligned:
    suggest-new: true
  nestif:
    min-complexity: 4
  gocyclo:
    min-complexity: 10
  nolintlint:
    require-explanation: true
    require-specific: true

linters:
  disable-all: true
  enable:
    - asciicheck
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl
    - errcheck
    - funlen
    # - gochecknoglobals
    # - gochecknoinits
    # - gocognit
    - goconst
    - gocritic
    # - gocyclo
    - godot
    - godox
    - gofmt
    - goimports
    - golint
    # - gomnd
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - interfacer
    - lll
    - maligned
    - misspell
    - nakedret
    - nestif
    - nolintlint
    - prealloc
    - rowserrcheck
    - scopelint
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace
    # - wsl

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
